server:
  port: 8082
  servlet:
    context-path: /api

spring:
  application:
    name: rewards-service
  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: rewards-service-group
      bootstrap-servers: localhost:9092

kafka:
  bootstrap-servers: localhost:9092
  group-id: rewards-service-group

talonone:
  api-key: "YOUR_TALONONE_API_KEY"
  base-url: "https://api.talon.one"
  application-id: "YOUR_TALONONE_APPLICATION_ID"
  campaign-id: "YOUR_TALONONE_CAMPAIGN_ID"

logging:
  level:
    root: INFO
    com.example.rewards: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"

# Swagger/OpenAPI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
