spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Talon.One API configuration
# Replace with your actual Talon.One API URL and API key
# Example: https://yourcompany.talon.one
# Example: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

talonone:
  api:
    url: https://yourcompany.talon.one
    key: your-talonone-api-key

server:
  port: 8080
